# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information about this task.', null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='task',
            name='identifier',
            field=models.SlugField(blank=True, help_text='The unambiguous internal identifier of this task.', max_length=256, null=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='task',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this task.', max_length=256, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attribute',
            field=models.ForeignKey(blank=True, help_text='The attribute this task is refering to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='domain.Attribute', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='task',
            name='conditions',
            field=models.ManyToManyField(blank=True, help_text='The list of conditions evaluated for this task.', to='conditions.Condition', verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_de',
            field=models.CharField(help_text='The German text for this task.', max_length=256, verbose_name='Text (de)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_en',
            field=models.CharField(help_text='The English text for this task.', max_length=256, verbose_name='Text (en)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_period',
            field=models.DurationField(help_text='The the time period after this task becomes active.', verbose_name='Time period'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_de',
            field=models.CharField(help_text='The German title for this task.', max_length=256, verbose_name='Title (de)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_en',
            field=models.CharField(help_text='The English title for this task.', max_length=256, verbose_name='Title (en)'),
        ),
    ]
