# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 16:18
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def create_identifier(apps, schema_editor):

    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        if not task.identifier:
            task.identifier = slugify(task.text_en)
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_refactoring'),
    ]

    operations = [
        migrations.RunPython(create_identifier),
    ]
