# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_refactoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='uri',
            field=models.URLField(blank=True, help_text='The Uniform Resource Identifier of this view.', max_length=256, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='view',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information about this view.', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='view',
            name='identifier',
            field=models.SlugField(help_text='The unambiguous internal identifier of this view.', max_length=256, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='view',
            name='template',
            field=models.TextField(blank=True, help_text='The template for this view, written in Django template language.', null=True, verbose_name='Template'),
        ),
    ]
