# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0004_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionset',
            options={'ordering': ('identifier',), 'verbose_name': 'OptionSet', 'verbose_name_plural': 'OptionSets'},
        ),
        migrations.RenameField(
            model_name='option',
            old_name='title',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='optionset',
            old_name='title',
            new_name='identifier',
        ),
    ]
