# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='identifier',
            field=models.SlugField(default=None, help_text='The unambiguous internal identifier of this catalog.', max_length=128, unique=True, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionentity',
            name='identifier',
            field=models.SlugField(default=None, help_text='The unambiguous internal identifier of this question/questionset.', max_length=128, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='identifier',
            field=models.SlugField(default=None, help_text='The unambiguous internal identifier of this section.', max_length=128, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsection',
            name='identifier',
            field=models.SlugField(default=None, help_text='The unambiguous internal identifier of this subsection.', max_length=128, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('catalog', 'identifier')]),
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together=set([('section', 'identifier')]),
        ),
    ]
