# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0009_options'),
        ('options', '0006_refactoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('identifier',), 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='title',
            new_name='identifier',
        ),
    ]
