# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0026_refactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeentity',
            name='identifier',
            field=models.SlugField(help_text='Unambiguous internal identifier of this attribute/entity.', max_length=128, verbose_name='Identifier'),
        ),
    ]
